#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-googleVis
Version  : 0.7.3
Release  : 55
URL      : https://cran.r-project.org/src/contrib/googleVis_0.7.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/googleVis_0.7.3.tar.gz
Summary  : R Interface to Google Charts
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-jsonlite
BuildRequires : R-jsonlite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
to create interactive charts based on data frames. Charts
    are displayed locally via the R HTTP help server. A modern
    browser with an Internet connection is required. The data 
    remains local and is not uploaded to Google.

%prep
%setup -q -n googleVis
pushd ..
cp -a googleVis buildavx2
popd
pushd ..
cp -a googleVis buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716761925

%install
export SOURCE_DATE_EPOCH=1716761925
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/googleVis/CITATION
/usr/lib64/R/library/googleVis/DESCRIPTION
/usr/lib64/R/library/googleVis/INDEX
/usr/lib64/R/library/googleVis/Meta/Rd.rds
/usr/lib64/R/library/googleVis/Meta/data.rds
/usr/lib64/R/library/googleVis/Meta/demo.rds
/usr/lib64/R/library/googleVis/Meta/features.rds
/usr/lib64/R/library/googleVis/Meta/hsearch.rds
/usr/lib64/R/library/googleVis/Meta/links.rds
/usr/lib64/R/library/googleVis/Meta/nsInfo.rds
/usr/lib64/R/library/googleVis/Meta/package.rds
/usr/lib64/R/library/googleVis/Meta/vignette.rds
/usr/lib64/R/library/googleVis/NAMESPACE
/usr/lib64/R/library/googleVis/NEWS.md
/usr/lib64/R/library/googleVis/R/googleVis
/usr/lib64/R/library/googleVis/R/googleVis.rdb
/usr/lib64/R/library/googleVis/R/googleVis.rdx
/usr/lib64/R/library/googleVis/data/Rdata.rdb
/usr/lib64/R/library/googleVis/data/Rdata.rds
/usr/lib64/R/library/googleVis/data/Rdata.rdx
/usr/lib64/R/library/googleVis/demo/EventListener.R
/usr/lib64/R/library/googleVis/demo/Roles.R
/usr/lib64/R/library/googleVis/demo/Trendlines.R
/usr/lib64/R/library/googleVis/demo/googleVis.R
/usr/lib64/R/library/googleVis/doc/googleVis_examples.R
/usr/lib64/R/library/googleVis/doc/googleVis_examples.Rmd
/usr/lib64/R/library/googleVis/doc/googleVis_examples.html
/usr/lib64/R/library/googleVis/doc/googleVis_intro.R
/usr/lib64/R/library/googleVis/doc/googleVis_intro.Rmd
/usr/lib64/R/library/googleVis/doc/googleVis_intro.html
/usr/lib64/R/library/googleVis/doc/index.html
/usr/lib64/R/library/googleVis/googleVis_hexagon.R
/usr/lib64/R/library/googleVis/help/AnIndex
/usr/lib64/R/library/googleVis/help/aliases.rds
/usr/lib64/R/library/googleVis/help/figures/logo.png
/usr/lib64/R/library/googleVis/help/googleVis.rdb
/usr/lib64/R/library/googleVis/help/googleVis.rdx
/usr/lib64/R/library/googleVis/help/paths.rds
/usr/lib64/R/library/googleVis/html/00Index.html
/usr/lib64/R/library/googleVis/html/R.css
/usr/lib64/R/library/googleVis/mansections/GoogleChartToolsURL.txt
/usr/lib64/R/library/googleVis/mansections/GoogleChartToolsURLConfigOptions.txt
/usr/lib64/R/library/googleVis/mansections/gvisOptions.txt
/usr/lib64/R/library/googleVis/mansections/gvisOutputStructure.txt
/usr/lib64/R/library/googleVis/shiny/server.R
/usr/lib64/R/library/googleVis/shiny/ui.R
